#!/bin/bash
set -euo pipefail
# Custom yamllint wrapper that only lints Claude-generated YAML files
# Only processes files with the Claude header comment

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

CLAUDE_HEADER="# Generated by Claude - Home Assistant Configuration"
YAMLLINT_CONFIG="public/.yamllint.yml"
YAMLLINT="$PROJECT_DIR/venv/bin/yamllint"

# Check if yamllint is available
if [[ ! -x "$YAMLLINT" ]]; then
    echo "yamllint not found in venv, skipping."
    exit 0
fi

EXIT_CODE=0

# Filter files to only include Claude-generated ones
CLAUDE_FILES=()

for file in "$@"; do
    # Check if it's a YAML file
    if [[ "$file" =~ \.(yaml|yml)$ ]]; then
        # Check if file exists and has Claude header
        if [[ -f "$file" ]] && head -3 "$file" 2>/dev/null | grep -Fq "$CLAUDE_HEADER"; then
            CLAUDE_FILES+=("$file")
            echo "Will lint Claude-generated file: $file"
        else
            echo "Skipping non-Claude file: $file"
        fi
    fi
done

# Run yamllint only on Claude-generated files
if [ ${#CLAUDE_FILES[@]} -gt 0 ]; then
    echo "Running yamllint on ${#CLAUDE_FILES[@]} Claude-generated YAML files..."
    "$YAMLLINT" -c "$YAMLLINT_CONFIG" "${CLAUDE_FILES[@]}" || EXIT_CODE=$?
else
    echo "No Claude-generated YAML files to lint."
fi

exit $EXIT_CODE
