// Generated by setup-customize on 2026-06-06. Edit to adjust entity assignments.

export interface RoomConfig {
  id: string;
  name: string;
  /** Floor number: -1=basement, 0=outside, 1=first, 2=second, 3=attic */
  floor: number;
  lights: string[];
  occupancySensor?: string;
  temperatureSensor?: string;
  humiditySensor?: string;
  co2Sensor?: string;
  illuminanceSensor?: string;
  noiseSensor?: string;
  pressureSensor?: string;
  aqiSensor?: string;
  temperatureRate?: string;
  mediaPlayers?: string[];
  climate?: string[];
  covers?: string[];
  contactSensors?: { entity: string; label: string; type?: "door" | "window" }[];
  zoneOccupancy?: { entity: string; label: string }[];
  effectiveTarget?: string;
  remoteEntity?: string;
  sleepTimer?: string;
  tvPlatform?: string;
  volumeEntity?: string;
}

export const ROOMS: RoomConfig[] = [
  // ── First Floor ──────────────────────────────────────────────────────────
  {
    id: "living_room",
    name: "Living Room",
    floor: 1,
    lights: [
      "light.living_room_lights",
      "light.wled_living_room",
      "light.wled_tv_living_room",
    ],
    climate: ["climate.downstairs"],
    mediaPlayers: ["media_player.apple_tv_living_room"],
    remoteEntity: "remote.apple_tv_living_room",
    tvPlatform: "apple_tv",
    temperatureSensor: "sensor.downstairs_temperature",
    humiditySensor: "sensor.downstairs_humidity",
    covers: ["cover.somfy_motorized_shade_4", "cover.somfy_motorized_shade_6"],
  },
  {
    id: "dining",
    name: "Dining",
    floor: 1,
    lights: [
      "light.600w_dimmer_3",
      "light.600w_dimmer_8",
      "light.600w_dimmer_9",
      "light.600w_dimmer_19",
      "light.scene_capable_switch_on_off_2",
    ],
    mediaPlayers: ["media_player.unnamed_room"],
  },
  {
    id: "guest_bedroom",
    name: "Guest Bedroom",
    floor: 1,
    lights: ["light.600w_dimmer_22", "light.scene_capable_switch_on_off_11"],
  },
  {
    id: "gym",
    name: "Gym",
    floor: 1,
    lights: ["light.600w_dimmer_7"],
    mediaPlayers: ["media_player.family_room_2"],
  },
  {
    id: "garage",
    name: "Garage",
    floor: 1,
    lights: ["light.ratgdov25_75423c_light", "light.ratgdov25_b490de_light"],
    occupancySensor: "binary_sensor.ratgdov25_75423c_motion",
    mediaPlayers: ["media_player.unnamed_room_3"],
    temperatureSensor: "sensor.garage_temperature",
    humiditySensor: "sensor.garage_humidity",
    covers: ["cover.ratgdov25_75423c_door"],
  },
  {
    id: "office",
    name: "Office",
    floor: 1,
    lights: ["light.office_lights"],
    occupancySensor:
      "binary_sensor.door_window_sensor_7_pro_home_security_motion_detection_location_provided",
    mediaPlayers: ["media_player.apple_tv_office"],
    remoteEntity: "remote.apple_tv_office",
    tvPlatform: "apple_tv",
  },
  {
    id: "main_entrance",
    name: "Main Entrance",
    floor: 1,
    lights: [],
    covers: ["cover.somfy_motorized_shade_2"],
  },
  {
    id: "hallways",
    name: "Hallways",
    floor: 1,
    lights: [
      "light.600w_dimmer",
      "light.600w_dimmer_2",
      "light.600w_dimmer_4",
      "light.600w_dimmer_15",
      "light.600w_dimmer_16",
    ],
    covers: ["cover.somfy_motorized_shade_3"],
  },

  // ── Second Floor ─────────────────────────────────────────────────────────
  {
    id: "master_bedroom",
    name: "Master Bedroom",
    floor: 2,
    lights: ["light.master_bdrm_lights"],
    climate: ["climate.master_bedroom"],
    mediaPlayers: ["media_player.unnamed_room_2"],
    temperatureSensor: "sensor.master_bedroom_temperature",
    humiditySensor: "sensor.master_bedroom_humidity",
  },
  {
    id: "master_bathroom",
    name: "Master Bathroom",
    floor: 2,
    lights: [
      "light.master_bathroom",
      "light.scene_capable_switch_on_off_13",
      "light.scene_capable_switch_on_off_14",
      "light.scene_capable_switch_on_off_16",
      "light.scene_capable_switch_on_off_basic",
    ],
  },
  {
    id: "girls_bathroom",
    name: "Girls' Bathroom",
    floor: 2,
    lights: [
      "light.scene_capable_switch_on_off_9",
      "light.scene_capable_switch_on_off_10",
    ],
  },
  {
    id: "laras_bedroom",
    name: "Lara's Bedroom",
    floor: 2,
    lights: ["light.600w_dimmer_12"],
    mediaPlayers: ["media_player.unnamed_room_6"],
  },
  {
    id: "mayas_bedroom",
    name: "Maya's Bedroom",
    floor: 2,
    lights: ["light.girls_lights"],
    mediaPlayers: ["media_player.unnamed_room_5"],
  },
  {
    id: "music_room",
    name: "Music Room",
    floor: 2,
    lights: ["light.600w_dimmer_10"],
    climate: ["climate.family_room"],
    mediaPlayers: ["media_player.unnamed_room_4"],
    temperatureSensor: "sensor.family_room_temperature",
    humiditySensor: "sensor.family_room_humidity",
  },
  {
    id: "laundry_room",
    name: "Laundry",
    floor: 2,
    lights: [],
  },
  {
    id: "hallways_2f",
    name: "Hallways 2F",
    floor: 2,
    lights: [],
  },

  // ── Basement ─────────────────────────────────────────────────────────────
  {
    id: "basement",
    name: "Basement",
    floor: -1,
    lights: ["light.basement_lights"],
    temperatureSensor: "sensor.basement_temperature",
    humiditySensor: "sensor.basement_humidity",
  },

  // ── Attic ─────────────────────────────────────────────────────────────────
  {
    id: "attic",
    name: "Attic",
    floor: 3,
    lights: [],
    temperatureSensor: "sensor.esphome_web_2d3c82_temperature",
    humiditySensor: "sensor.esphome_web_2d3c82_humidity",
  },

  // ── Outside ───────────────────────────────────────────────────────────────
  {
    id: "outside",
    name: "Outside",
    floor: 0,
    lights: [
      "light.600w_dimmer_6",
      "light.wled_front_door",
      "light.scene_capable_switch_on_off_5",
      "light.scene_capable_switch_on_off_6",
      "light.scene_capable_switch_on_off_7",
    ],
    occupancySensor: "binary_sensor.garage_motion",
  },
];

// Maps HA username (lowercase) → room id for pinned view on login
export const USER_ROOM_MAP: Record<string, string> = {};
