// Generated by setup-customize on 2026-06-06. Edit to adjust entity IDs and configs.
// Items marked TODO need corresponding helpers created in HA first.

// ── Config type definitions ────────────────────────────────────────────────

export interface HeaderConfig {
  climateMode: string;
  outdoorTemp: string;
  weather: string;
  persons: Array<{ id: string; name: string; picture?: string }>;
}

export interface ContextConfig {
  timeOfDay: string;
  boilerEntity: string;
  solarPower: string;
  loadPower: string;
  chargerPower: string;
  chargerPowerOffered: string;
  chargerStatus: string;
  evBattery: string;
  evCharging: string;
  weather: string;
  outdoorTemp: string;
  precipitation?: string;
  indoorPressure?: string;
  forecastLow?: string;
  forecastHigh?: string;
}

export interface ActiveAutomationsConfig {
  nightMode: string;
  movieMode: string;
  workMode: string;
  awayMode: string;
  lrAc: string;
  brAc: string;
  sparePower?: string;
  chargerStatus: string;
  evCharging: string;
  chargerPower: string;
  chargerPowerOffered: string;
}

export interface QuickActionsConfig {
  timeOfDay: string;
  projector?: string;
  nightMode: string;
  movieMode: string;
  workMode: string;
  awayMode: string;
}

export interface VacuumConfig {
  vacuum: string;
  battery: string;
  movement: string;
  cleaningMode: string;
  turboMode: string;
  lamp: string;
  power: string;
}

export interface CameraConfig {
  id: string;
  name: string;
  /** Primary camera entity used for streaming */
  entity: string;
  batterySensor?: string;
  eventImage?: string;
  personSensor: string;
  wifiSensor?: string;
  chargingSensor?: string;
  /** go2rtc stream name for MSE/WebRTC (defaults to id) */
  go2rtcStream?: string;
  /** Whether this camera also controls a gate lock */
  hasGateLock?: boolean;
}

export type ScheduleEditorConfig = Array<{
  title: string;
  items: Array<{ entity: string; label: string; icon: string }>;
}>;

export interface TempPresetsConfig {
  climateModeEntity: string;
  heatingPresets: Array<{ entity: string; label: string; icon: string; min: number; max: number }>;
  coolingPresets: Array<{ entity: string; label: string; icon: string; min: number; max: number }>;
}

// ── Modes ─────────────────────────────────────────────────────────────────
// TODO: create these in HA → Settings → Helpers → Add input_boolean for each
export const NIGHT_MODE    = "input_boolean.night_mode";
export const MOVIE_MODE    = "input_boolean.movie_mode";
export const WORK_MODE     = "input_boolean.work_mode";
export const AWAY_MODE     = "input_boolean.away_mode";
export const NIGHT_ALERTS  = "input_boolean.night_alerts";

// TODO: create input_select.climate_mode with options: Heating, Cooling, Off
export const CLIMATE_MODE = "input_select.climate_mode";

// TODO: create input_datetime.next_climate_transition
export const NEXT_CLIMATE_TRANSITION = "input_datetime.next_climate_transition";

// TODO: create input_select.time_of_day with options: morning, day, evening, night
export const TIME_OF_DAY = "input_select.time_of_day";

// ── Motion light timeouts (input_number helpers — create in HA) ───────────
export const TIMEOUT_MOTION_NORMAL       = "input_number.timeout_motion_normal";
export const TIMEOUT_MOTION_NORMAL_LONG  = "input_number.timeout_motion_normal_long";
export const TIMEOUT_MOTION_NIGHT        = "input_number.timeout_motion_night";
export const TIMEOUT_MOTION_NIGHT_SHORT  = "input_number.timeout_motion_night_short";
export const TIMEOUT_MOTION_MOVIE        = "input_number.timeout_motion_movie";

// ── Light transition durations (input_number helpers — create in HA) ────────
// TODO: create input_number.transition_on and input_number.transition_off in HA
export const TRANSITION_ON  = "input_number.transition_on";
export const TRANSITION_OFF = "input_number.transition_off";

// ── Solar & Power (Tesla Powerwall) ───────────────────────────────────────
export const SOLAR_POWER   = "sensor.powerwall_solar_now";
export const LOAD_POWER    = "sensor.powerwall_load_now";
export const GRID_POWER    = "sensor.powerwall_site_now";

// ── EV (Tesla "Sky") ─────────────────────────────────────────────────────
export const EV_BATTERY            = "sensor.sky_battery";
export const EV_CHARGER_POWER      = "sensor.sky_charger_power";
export const EV_CHARGER_STATUS     = "binary_sensor.sky_charger";
export const EV_CHARGING           = "switch.sky_charger";
// TODO: if Sky exposes a charger_power_offered sensor, add here
export const EV_CHARGER_POWER_OFFERED = "";

// ── System monitoring ─────────────────────────────────────────────────────
export const SYSTEM_CPU       = "sensor.processor_use_percent";
export const SYSTEM_RAM       = "sensor.memory_use_percent";
export const SYSTEM_DISK      = "sensor.disk_use_percent_config";
export const SYSTEM_LAST_BOOT = "sensor.last_boot";
export const STALE_THRESHOLD_MS = 3_600_000; // 1 hour

// ── Security ─────────────────────────────────────────────────────────────
// TODO: wire a switch/lock entity for your gate if you have one
export const GATE_LOCK        = "";
export const DOORBELL_RINGING = "camera.main_door_last_ring";
export const SNAPSHOT_SAVE_CAMERA = "camera.main_door_live";

// ── Dishwasher (set to "" if you don't have one) ─────────────────────────
export const DISHWASHER_STATUS        = "";
export const DISHWASHER_TIME_REMAINING = "";

// ── Climate zone map: room id → zone descriptor ──────────────────────────
// Used by ClimateSection to show zone-level thermostat controls.
export interface ZoneDescriptor {
  name: string;
  /** Temperature sensor for the zone */
  sensorId: string;
  /** input_boolean for manual zone override */
  overrideBoolean: string;
  /** input_number for override target temperature */
  overrideTarget: string;
  /** Effective target entity (computed or override) */
  targetId: string;
  /** Optional AC entity for this zone */
  acEntity?: string;
}

export const ROOM_ZONE_MAP: Record<string, ZoneDescriptor> = {
  living_room: {
    name: "Downstairs",
    sensorId:        "sensor.downstairs_temperature",
    overrideBoolean: "input_boolean.zone_override_downstairs",
    overrideTarget:  "input_number.zone_target_downstairs",
    targetId:        "sensor.zone_effective_target_downstairs",
    acEntity:        "climate.downstairs",
  },
  master_bedroom: {
    name: "Master Bedroom",
    sensorId:        "sensor.master_bedroom_temperature",
    overrideBoolean: "input_boolean.zone_override_master",
    overrideTarget:  "input_number.zone_target_master",
    targetId:        "sensor.zone_effective_target_master_bed",
    acEntity:        "climate.master_bedroom",
  },
  music_room: {
    name: "Family Room",
    sensorId:        "sensor.family_room_temperature",
    overrideBoolean: "input_boolean.zone_override_family",
    overrideTarget:  "input_number.zone_target_family",
    targetId:        "sensor.zone_effective_target_family_room",
    acEntity:        "climate.family_room",
  },
};

// ── Weather ───────────────────────────────────────────────────────────────
export const WEATHER = "weather.dream_home";

// ── Cameras ───────────────────────────────────────────────────────────────
export const CAMERAS: CameraConfig[] = [
  {
    id: "doorbell",
    name: "Front Door",
    entity: "camera.main_door_live",
    eventImage: "camera.main_door_last_ring",
    personSensor: "binary_sensor.g5_pro_person_detected",
  },
  {
    id: "garage_outside",
    name: "Garage Outside",
    entity: "camera.garage_outside_medium_resolution_channel",
    eventImage: "camera.garage_outside_medium_resolution_channel",
    personSensor: "binary_sensor.garage_outside_person_detected",
  },
  {
    id: "front_door",
    name: "Front Camera",
    entity: "camera.front_door_medium_resolution_channel",
    eventImage: "camera.front_door_medium_resolution_channel",
    personSensor: "binary_sensor.g5_pro_person_detected",
  },
  {
    id: "garage_inside",
    name: "Garage Inside",
    entity: "camera.garage_inside_medium_resolution_channel",
    eventImage: "camera.garage_inside_medium_resolution_channel",
    personSensor: "binary_sensor.garage_inside_person_detected",
  },
  {
    id: "backyard",
    name: "Backyard",
    entity: "camera.g4_bullet_high",
    eventImage: "camera.g4_bullet_high",
    personSensor: "binary_sensor.g4_bullet_detections_motion",
  },
];

// ── Header (top bar) ─────────────────────────────────────────────────────
export const HEADER_CONFIG: HeaderConfig = {
  climateMode: CLIMATE_MODE,
  outdoorTemp: "sensor.outdoor_temperature_now",
  weather: WEATHER,
  persons: [
    { id: "person.hori_goller",  name: "Hori" },
    { id: "person.anca_goller",  name: "Anca" },
    { id: "person.maya",         name: "Maya" },
  ],
};

// ── Context card (home summary) ──────────────────────────────────────────
export const CONTEXT_CONFIG: ContextConfig = {
  timeOfDay:           TIME_OF_DAY,
  boilerEntity:        "climate.downstairs",
  solarPower:          SOLAR_POWER,
  loadPower:           LOAD_POWER,
  chargerPower:        EV_CHARGER_POWER,
  chargerPowerOffered: EV_CHARGER_POWER_OFFERED,
  chargerStatus:       EV_CHARGER_STATUS,
  evBattery:           EV_BATTERY,
  evCharging:          EV_CHARGING,
  weather:             WEATHER,
  outdoorTemp:         "sensor.outdoor_temperature_now",
  precipitation:       "sensor.precipitation_next_hour",
};

// ── Quick actions (mode toggles on home screen) ───────────────────────────
export const QUICK_ACTIONS_CONFIG: QuickActionsConfig = {
  timeOfDay: TIME_OF_DAY,
  nightMode: NIGHT_MODE,
  movieMode: MOVIE_MODE,
  workMode:  WORK_MODE,
  awayMode:  AWAY_MODE,
};

// ── Active automations summary card ──────────────────────────────────────
export const ACTIVE_AUTOMATIONS_CONFIG: ActiveAutomationsConfig = {
  nightMode:           NIGHT_MODE,
  movieMode:           MOVIE_MODE,
  workMode:            WORK_MODE,
  awayMode:            AWAY_MODE,
  lrAc:                "climate.downstairs",
  brAc:                "climate.master_bedroom",
  chargerStatus:       EV_CHARGER_STATUS,
  evCharging:          EV_CHARGING,
  chargerPower:        EV_CHARGER_POWER,
  chargerPowerOffered: EV_CHARGER_POWER_OFFERED,
};

// ── Vacuum (set to empty strings if you don't have one) ──────────────────
export const VACUUM_CONFIG: VacuumConfig = {
  vacuum:       "",
  battery:      "",
  movement:     "",
  cleaningMode: "",
  turboMode:    "",
  lamp:         "",
  power:        "",
};

// ── Schedule editor (input_datetime helpers — create in HA) ───────────────
export const SCHEDULE_EDITOR_CONFIG: ScheduleEditorConfig = [
  {
    title: "Lighting",
    items: [
      // TODO: create input_datetime.lights_on_morning in HA
      // { entity: "input_datetime.lights_on_morning", label: "Morning on", icon: "mdi:weather-sunset-up" },
      // { entity: "input_datetime.lights_off_night",  label: "Night off",  icon: "mdi:weather-night" },
    ],
  },
];

// ── Temperature presets ───────────────────────────────────────────────────
export const TEMP_PRESETS_CONFIG: TempPresetsConfig = {
  climateModeEntity: CLIMATE_MODE,
  heatingPresets: [
    // TODO: create input_number helpers for each preset in HA
    // { entity: "input_number.temp_preset_day",   label: "Day",   icon: "mdi:weather-sunny",  min: 60, max: 75 },
    // { entity: "input_number.temp_preset_night", label: "Night", icon: "mdi:weather-night",  min: 60, max: 72 },
    // { entity: "input_number.temp_preset_away",  label: "Away",  icon: "mdi:home-export-outline", min: 55, max: 70 },
  ],
  coolingPresets: [],
};

// ── Energy view ──────────────────────────────────────────────────────────────

/** Entity ID for Forecast.Solar power sensor. Empty = no integration configured. */
export const SOLAR_FORECAST_NOW = ""; // No Forecast.Solar integration configured

export interface EnergyConfig {
  solarPower: string;
  loadPower: string;
  gridNow: string;
  batteryNow: string;
  batteryCharge: string;
  batteryBackup: string;
  gridStatus: string;
  chargerPowerImport: string;
  chargerStatus: string;
}

export interface EvStatusConfig {
  carLabel: string;
  evBattery: string;
  evRange: string;
  evCharging: string;   // binary_sensor
  evCharger: string;    // binary_sensor (cable)
  evChargerPower: string;
  evChargeLimit: string;
  evTimeToFull: string;
  evEnergyAdded: string;
  evScheduledCharging: string;
  evChargeSwitch: string;  // switch entity for on/off
}

export interface WallConnectorConfig {
  status: string;          // sensor: ready/charging/not_connected/etc.
  vehicleConnected: string; // binary_sensor
  totalPower: string;       // sensor kW
  sessionEnergy: string;   // sensor kWh
  phaseACurrent: string;   // sensor A
  phaseBCurrent: string;
  phaseCurrent: string;
}

export interface SolarChartConfig {
  solarPower: string;
  loadPower: string;
  gridPower: string;
  chargerPowerImport: string;
  chargerPowerOffered: string;
  chargerStatus: string;
  electricityPriceGrid?: number;
  electricityPriceExport?: number;
}

export const ENERGY_CONFIG: EnergyConfig = {
  solarPower:         "sensor.powerwall_solar_now",
  loadPower:          "sensor.powerwall_load_now",
  gridNow:            "sensor.powerwall_site_now",
  batteryNow:         "sensor.powerwall_battery_now",
  batteryCharge:      "sensor.powerwall_charge",
  batteryBackup:      "sensor.powerwall_backup_reserve",
  gridStatus:         "binary_sensor.grid_status",
  chargerPowerImport: "sensor.asterix_charger_power",
  chargerStatus:      "binary_sensor.asterix_charging",
};

export const EV_STATUS_CONFIG: EvStatusConfig = {
  carLabel:            "Asterix",
  evBattery:           "sensor.asterix_battery",
  evRange:             "sensor.asterix_range",
  evCharging:          "binary_sensor.asterix_charging",
  evCharger:           "binary_sensor.asterix_charger",
  evChargerPower:      "sensor.asterix_charger_power",
  evChargeLimit:       "number.asterix_charge_limit",
  evTimeToFull:        "sensor.asterix_time_charge_complete",
  evEnergyAdded:       "sensor.asterix_energy_added",
  evScheduledCharging: "binary_sensor.asterix_scheduled_charging",
  evChargeSwitch:      "switch.asterix_charger",
};

export const OBELIX_STATUS_CONFIG: EvStatusConfig = {
  carLabel:            "Obelix",
  evBattery:           "sensor.sky_battery",
  evRange:             "sensor.sky_range",
  evCharging:          "binary_sensor.sky_charging",
  evCharger:           "binary_sensor.sky_charger",
  evChargerPower:      "sensor.sky_charger_power",
  evChargeLimit:       "number.sky_charge_limit",
  evTimeToFull:        "sensor.sky_time_charge_complete",
  evEnergyAdded:       "sensor.sky_energy_added",
  evScheduledCharging: "binary_sensor.sky_scheduled_charging",
  evChargeSwitch:      "switch.sky_charger",
};

export const WALL_CONNECTOR_CONFIG: WallConnectorConfig = {
  status:           "sensor.tesla_wall_connector_status",
  vehicleConnected: "binary_sensor.tesla_wall_connector_vehicle_connected",
  totalPower:       "sensor.tesla_wall_connector_total_power",
  sessionEnergy:    "sensor.tesla_wall_connector_session_energy",
  phaseACurrent:    "sensor.tesla_wall_connector_phase_a_current",
  phaseBCurrent:    "sensor.tesla_wall_connector_phase_b_current",
  phaseCurrent:     "sensor.tesla_wall_connector_phase_c_current",
};

export const SOLAR_CHART_CONFIG: SolarChartConfig = {
  solarPower:         "sensor.powerwall_solar_now",
  loadPower:          "sensor.powerwall_load_now",
  gridPower:          "sensor.powerwall_site_now",
  chargerPowerImport: "sensor.asterix_charger_power",
  chargerPowerOffered:"",
  chargerStatus:      "binary_sensor.asterix_charging",
};
